### ISSUE TITLE
Eventhubs sdk should work with iothub connection string.

### ISSUE THREAD

**Issue by amarzavery** [shkreza/eventhub-viewer#1]
@shkreza -I was looking at the source code in this repo..  Awesome work!!  I think the file ./lib/events.ts is missing in the repo.

Just wanted to let you know that, the event hubs sdk can handle the iothub connection string as well as shown in this example over [here](https://github.com/Azure/azure-event-hubs-node/tree/master/client#example-6---create-an-eventhubclient-from-an-iothub-connection-string). It will internally catch the redirect error and communicate with the corresponding event hub endpoint received from the redirect error thereby saving time for the end user to get the associated eventhub connection string.

**Comment by shkreza** [comment]
I fixed this! [Commit#070fb6a](https://github.com/shkreza/eventhub-viewer/commit/070fb6a4dd50ce482bbd0ea3684bb0d0c2e78c2b#diff-a084b794bc0759e7a6b77810e01874f2)

Somehow `lib/events.ts` was added to my `.gitignore` and was masking this file!!!! :-)

This file is just a little wrapper around `EventHubClient.receiveBatch()` and pumps events into a `Transform` object so they can be shipped over to the web UI incrementally (event-by-event).

**Comment by amarzavery** [comment]
That is cool. Did you check the other comment about passing the iothub connection string?

**Comment by shkreza** [comment]
oh nice! I didn't know about this method.. I am guessing I can either add another field to get IoT connection string from user, or is there a way/method to distinguish whether user's connection string is for IoT hub or event hubs? Then I can do it w/o a new field.

**Comment by amarzavery** [comment]
The Eventhub connectionstring has `Endpoint=<something>;....` and the iothub connectionstring has `Hostname=<something>;....` as the differentiating factor. That should tell you whether it is an EH or IotHub connection string. For reference you can take a look at the parsed models from both the connection string and the function to parse connection string over [here](https://github.com/Azure/azure-event-hubs-node/blob/master/client/lib/util/utils.ts#L26-L61).

**Comment by amarzavery** [comment]
The only thing to take notice of is: [createFromConnectionString](https://github.com/Azure/azure-event-hubs-node/blob/master/client/lib/eventHubClient.ts#L313) returns the EventHubClient if everything is fine whereas the [createFromIotHubConnectionString](https://github.com/Azure/azure-event-hubs-node/blob/master/client/lib/eventHubClient.ts#L333) returns a `Promise<EventHubClient>`. Because it needs to send a request to the IotHub hostname, get a redirect error which contains the EventHubClient endpoint and then return with the Eventhub client.

**Comment by shkreza** [comment]
Yep, that makes sense. I'll make the change this weekend.

**Comment by amarzavery** [comment]
@shkreza - I have published a new version 0.2.2 version of azure-event-hubs which exposes a function `isIotHubConnectionString(connectionString)` which indicates whether the given string is an iothub connection string or not. Please feel free to use that.

**Comment by shkreza** [comment]
oh very nice! I actually gave it a first go last night with string.includes() - it did work but I wasn't happy with it since it can have some corner cases. I like how you do it with `parseConnectionString`. I'll use your new package.

**Comment by shkreza** [comment]
if you are on campus let's get together for lunch some day? you seem very passionate and I'd also like to get some advice on swagger (which you seem to be an expert in ;)

**Comment by amarzavery** [comment]
Sure. Let's meet some time for lunch. I just found out that you work at MSFT as well. Will send you a Skype invite.

**Comment by shkreza** [comment]
Yep - I'm new in the IoT space!

BTW, I committed/deployed the change as well, although only with some minimal testing ;)

**Comment by amarzavery** [comment]
Yup. I did basic testing of it and it seems to be working well 👍
